dist: trusty
sudo: required
install: sudo bash -c "$(curl -fsSL https://s3.amazonaws.com/tools.nanobox.io/bootstrap/ci.sh)"

jobs:
  include:
    - stage: test
      env:
        - MIX_ENV=test
      script:
        - nanobox evar add MIX_ENV=test 
        - nanobox run mix coveralls.travis
      if: branch IN (develop, master)
    - stage: test
      env:
        - MIX_ENV=test
      script: nanobox run mix credo --only warning
      if: branch IN (develop, master)
    - stage: deploy-staging
      if: branch = develop
      script: 
        - nanobox remote add cubicon-b-dev
        - nanobox deploy
    - stage: deploy-production
      if: branch = master
      script:
        - nanobox remote add cubicon-b
        - nanobox deploy