dist: trusty
sudo: required
install: sudo bash -c "$(curl -fsSL https://s3.amazonaws.com/tools.nanobox.io/bootstrap/ci.sh)"

jobs:
  include:
    - stage: test
      script: nanobox run MIX_ENV="test" mix coveralls
      if: branch IN (develop, master)
    - stage: test
      script: nanobox run mix credo --only warning
      if: branch IN (develop, master)
    - stage: deploy-staging
      if: branch = develop
      script: 
        - nanobox remote add cubicon-b-dev
        - nanobox deploy
    - stage: deploy-production
      if: branch = master
      script:
        - nanobox remote add cubicon-b
        - nanobox deploy